import React, { useState } from "react";
import "../styles/Page24.css"; // Archivo de estilos
import { Link } from "react-router-dom"; 

function Page24() {
  const [currentPage, setCurrentPage] = useState(0);
  const [isFlipping, setIsFlipping] = useState(false);

  const pages = [
    { title: "Querida Heidy", content: 
      "Se que capaz no quieras leer esto despues de todo lo que ha pasado y si quieres no lo hagas, pero siempre desde pequeño me han enseñado que uno debe luchar hasta el final por lo que más ama, e incluso más cuando se trata del amor de tu vida. No quiero ser muy ostigante, no quiero quitarte tu tiempo o  que consideres esto ya como acoso pero necesito decirlo, tengo muchas cosas que no se por donde empezar. No se como tomar todo esto que esta pasando, literalmente parezco que no estoy en la faz de la tierra. Estos días han sido duros, dificiles y no te miento ya estoy cansado de llorar, uno no se pone feliz por perder al amor de su vida. No se si Marzo acabo con nosotros, al final las teorias que tanto te negaba ahora lo admito tenias razon, la estupida teoria de marzo dice que las personas que mas se aman tienden a romper en marzo por el cambio de invierno a primavera o algo asi si no me equivoco. Al final se cumplió. Bueno no solamente por culpa de eso, se que me dijiste que no me heche la culpa pero ya maduramente hablando tambien la tuve. Desde que me conociste siempre trate de darte lo mejor pero no me centre en corregir mis mismos errores o defectos de siempre, errores que hasta mis familiares me recalcan. Siempre he sido serio y enojon, antes más, es algo que saqué de mi papá y creeme que no me gusta nada. Es por eso que la ultima vez que nos vimos te hice la pregunta de que si tuvieramos un niño, el caracter de quien tendría. Fue por eso, porque no quisiera que mis hijos tengan mi caracter fuerte porque ahora ves los problemas que trae. Y aunque me digas que no, yo se que te fuiste desinteresando por mi caracter y por las muchas veces que estabamos peleando. Se qué no es sano y llega a ser toxico y entiendo tu cansancio."},
    { title: "", content: "Sé que lo estabas dando todo por salvar esto y yo no estaba colaborando y hasta te llegue a lastimar. No quiero justificarme pero si te das cuenta los ulltimos problemas fue desde que yo empece con esto de las prácticas, no supe manejar mi estres y tambien te estaba afectando a ti. Enserio perdoname, nunca lo hice con intención. Sabes, uno siempre se confía en una relación, que todo esta bien y eso me paso a mi. Y si te doy la razón, una relación a distancia llega a ser dificil y mas en este caso conmigo de ser de otra ciudad, creeme que lo entiendo, una mujer necesita estar acompañada, sentirse apoyada y amada siempre por su novio 24/7 y mas fisicamente. El hecho que no nos veiamos diariamente  también te llego a cansar, aunque me digas que no. Desde que te conocí siempre entendí que estabas haciendo la mayoria se las cosas sola debido a las circunstancias y siento que creiste que al tener novio ibas a tener una compañia siempre, pero yo no te pude brindar eso y se que eso no es lonque buscas. Yo sabía muy perfectamente y ultimamente trate de saldar eso, por eso estaba emocionado de que al salir de las practicas yo iba a verte todos los días. Creeme que no verte todos los dias igual tambien me fastidiaba tanto y si te pones a pensar es un contraste diferente a lonque viviamos los primeros días cuando nos veiamos todos los dias en vinculacion. Talvez tambien estabas cansada de hacer tremendo viajes desde tu casa hasta mi depa madrugando para al final terminar sin ropa y mil perdón por eso, admito que al final si me estaba sobrepasando, creeme que no lo hacia con malos pensamientos y mala intencion, no sabia de esa sensación hasta que llegaste tu y fue magico todas las veces que compartimos eso, pero no lo hice con malicia y no solamente queria que vengas por eso, solamente me gustaba que tengamos ese momento intimo. Pero admito también que debi ser más romantico y no solamente en ese sentido. Nunca hemos tenido una cena, salido en la noche o ya no haciamos un plan diferente, comprendo que le faltaba romanticismo a la relación y perdón por no dartelo. Ahora tambien afirmo que eso tambien es importante y no solamente dar prioridad a los momentos malos." },
    { title: "", content: "Como hablamos ese día en videollamada, es nuestra primera relación madura y capaz no supimos manejar el ritmo porque no teniamos experiencia tanto y nos afecto mucho mas esa transicion de cambio a nuestra vida adulta. Se que cada uno tiene metas o sueños diferentes, como por ejemplo tu comprarte la casita y a tu mami y yo comprarme mi carrito. Eso es lo que nos hace seguir en el camino y me alegra y enorgullece en el camino que estas haciendo haciendo. Enserio sentía muy bonito verte asi salir del trabajo, vestida formal con tu carterita y que me cuentes lo que hiciste, pero mas me llenaba de emoción pensar que eso en un futuro se iba a convertir algo del día día, yendote a ver al trabajo en mi carrito y llevarte a tu casa. Porque sí, yo ya me estaba planeado ya una vida contigo y no es mentira. Desde el primer te dije que dejaria toda mi vida en Ibarra para estar contigo y creeeme que esa promesa siempre estaba en mi cabeza. Es por eso que tambien estaba estresado con lo de las practicas porque enserio queria un futuro que nos beneficie a los dos. No te lo dije pero había dias que iba a Quito a ver departamentos para ya llevar un rumbo contigo pero ya sabes a veces la vida es injusta y te pone todas las trabas. Enserio queria  que nuestros dos sueños se complementen y ayudarnos mutuamente el uno y el otro. Queria y quiero hacer una vida contigo porque para serte sincero no creo que conozca a nadie con la misma mentalidad tuya, mentalidad de la cuale me enamoré. Yo, tu familia, amigos estamos demasiado orgullosos de la persona en que te has convertido, hay veces en las que yo digo en realidad que yo no soy suficiente para ti debido a que bueno eres todo lo opuesto a mi y en eso llevas una gran ventaja. En serio no dudes de ti y la gran capacidad que tienes. No sé en realidad los problemas que tienes o tuviste pero lo que si sé es que simpre los has sabido resolver, ya sea sola o acompañada y creeme que tuve la suerte de encontrar una mujer asi como tú. " },
    {title:"", content: "Siempre supe el porque decias que no eras suficiente para mi, pero bueno ese es un tema que se debe hablar en persona. Pero vulevo y te recalco, tu no sabes como llegaste a impactar mi vida y hablo para bien y para serte sincero no me he sentido tan bien hasta que empezo nuestra relación. Pero  tambien te voy a ser sincero en esto, el estar diciendole a tu pareja que no eres suficiente para ella, también le cansa a el otro, y creeme que yo tambien cierto día llegue aun punto donde te iba a terminar enserio y fue la primera vez que me lo dijiste despues de estar una semana separados, creeme que casi lo hago pero mejor quise a averiguar con el por qué pensabas eso y ahora lo sé. Quiero que tengas en cuenta que para mi siempre fuiste mas que suficiente, mas bien creía que yo no cumplía tus expectativas pero aun asi intentaba de estar a la altura. Yo sé que te reclamaba mucho y eso también te doblego esa autoestima y perdón por eso pero ya te digo mi caracter fuerte no respondia bien a eso. Entendí que no puedo cambiar esas pequeñas cosas que no me gustaban, pero es porque uno debe a amar a alguien tal y como es, con sus errores y fallas. Pero yo tambien insisti mucho en que cambies eso que llego a cansarte. Y en eso falle ya que tu me amaste y aguantabas con todos mis arrebatos y nunca me reclamaste, nunca dijiste nada y me duele mucho porque capaz eso te lastimaba o dolía. Perdoname mucho enserio. No quiero que cambies como eres porque aprendí de poco a poco entender tu personalidad, tus inseguridades, tus errores y cual es la causa de cada cosa que nombré y por eso trataba de aprender de ti cada día, disimulando haciendote preguntas. Pero como digo igual yo te conocí y te ame pero siempre vi a una chica hermosa con un noble y lindo corazón que siempre me supo dar todo. Y eso era lo que más me importaba. "},
    { title: "", content: "Sabes? Creo mucho en el amor y aunque otras personas me hayan fallado varias veces siempre digo que el amor es la escencia de una persona. Y sabes por qué mas creo en el amor? Me han fallado muchas veces y no hablo de exnovias, sino mi familia. Empezando por mi papá que le fue infiel a mi mamá pero creyeron en una segunda oportunidad y ahi estan juntos, a pesar de las peleas constantes y enojos, pero ahi están el uno para el otro y sé que el uno no puede vivir sin el otro. Mi abuelito, la persona que más admiro, no hace muchos años también le fallo a mi abuelita de la misma manera, pero fueron ellos que nos enseñaros que cuando amas a alguién, no habra mal que por bien no venga, ahora los ves a los dos feliz en su casita, solucionaron todo que yo crei que enserio no tenia arreglo. He visto casos de amigos que enserio no tenían solución alguna pero los miro ahora y estan felices apoyandose el uno al otro. Y es por esa y mil razones que creo en el amor, por el simple hecho de que siempre lo he visto morir y renacer. Me gusta, el amor, el romanticismo porque creo en él. El amor para mi no es algo subjetivo sino que es el alma o escencia de la otra persona. Porque sabes que ahí hay algo que te hace feliz, que te da paz, que te da confianza, que te da refugio y muchas cosas que puedo nombrar. En ti encontre todo eso. Uno no puede dejar de amar en 1 día y mucho menos olvidar en 2. Confieso que me dolió que me dijeras que ya no sientes nada por mí y que ya no me amas pero uno lo siente cuando pasa eso. Y yo no lo siento Heidy, aun siento mucho tu alma con la mía y se que suena fantasioso pero lo siento asi. Si no lo sintiera no estuviera escribiendo esto y pensando en ti. Y no por algo el destino nos puso juntos cuando ni tu camino ni el mio no tenian ni por donde cruzarse. Tu sabes muy bien que cuando estamos juntos fisicamente tanto el uno como el otro se siente en paz, en calidez y felicidad. O que solamente al vernos de lejos nos da esa seguridad y felicidad. Solo te dire que nunca puedes contradecir a tu corazón y mucho menos negarle a quien amas " },
    {title: "", content: "Ese domingo me preguntaste, que hubiera pasado si tu no me buscabas? No debías preguntarlo porque sabes muy bien que yo te buscaría siempre en esta y en otra vida. Quiero que entiendas que siempre te buscaré, solamente bromeaba ese día para hacerte tener iras pero enserio te buscaría hasta en un lugar que no existe. A mi no me importa mi orgullo, porque cuando se trata de quien amás eso no existe. Sé que puedo parecer que estoy rogando, que estoy suplicando, que esto de rodillas, pero es asi de cierta u otra manera pero a diferencia de que esto lo hago con toda la sinceridad y lo que siento. Quiero que sepas que esta carta no la hago solamente para que cambies de opinión o para tratar de arreglar las cosas, la hago porque me sale del corazón con toda la sinceridad y amor que puedo tener, que entiendas que es lo que pienso desde mi perspectiva y que no quiero dejar morir esto tan bonito. No quiero que pienses que igual te estoy obligando a una respuesta, si quieres me la das, sino no hay problema y si es asi, ojala el destino nos pueda unir en esta vida y si no es en esta, pues que sea en otra vida. Tampoco quiero que pienses que voy a estar de acosador insistiendo todo el tiempo porque tambien respeto tu espacio e integridad, solamente no queria quedarme con los brazos cruzados porque se que es tu cumpleaños y quiero que en verdad tengas un detalle bonito ya que no me dejas darte el que te habia comprado, asi que se me ocurrio hacer todo este codigo en React y espero que te guste y tengas un lindo recuerdo de esto. No se como te sientas en estos momentos, no se si te sientas mas tranquila o en paz o si estas triste pero solamente quiero que estes bien y feliz. De mi parte creeme que no es facil volver a mi yo de antes, mi yo solitario que no habla con nadie y creeme que se hace mas feo ahora encerrado en este cuarto frío sin poder contarle mi día a nadie. Es feo entender que un día tenias al amor de tu vida y el siguiente ya no, pero es algo que debo enfrentar. No es bonito volver a mi vida anterior pero no te preocupes .    "} 
    ,{title: "", content: "Quiero que sepas que si no te escribo o algo, no es porque no te extrañe. Creeme que tu ausencia duele mucho y no sabes la falta que me haces. Te extraño mucho a ti y a tus ojos "}
    ,{title: "", content: "Por ultimo y más importante. Te amo Heidy Rashell y aunque tu ya no lo hagas quiero que sepas que yo siempre lo hice, lo hago y lo haré. Te amo mucho enserio y si tengo que dar todo para volver a enamorarte creeme que hasta daria mucho mas de lo que tengo"}
    ,{title: "", content:"Te ama, te quiere y te adora. Con cariño : Johan Romo"}
    ,{title: "", content:"Te extraño..."}
  ];

  const handleNextPage = () => {
    if (currentPage < pages.length - 1) {
      setIsFlipping(true);
      setTimeout(() => {
        setCurrentPage(currentPage + 1);
        setIsFlipping(false);
      }, 1000); // Duración de la animación
    }
  };

  const handlePreviousPage = () => {
    if (currentPage > 0) {
      setIsFlipping(true);
      setTimeout(() => {
        setCurrentPage(currentPage - 1);
        setIsFlipping(false);
      }, 1000); // Duración de la animación
    }
  };

  return (
    <div className="book-container">
      
         <Link to="/" className="back-button">
      🏠 Regresar al menú
        </Link>
      <div className={`page ${isFlipping ? "flipping" : ""}`}>
        <div className="page-content">
          <h1>{pages[currentPage].title}</h1>
          <p>{pages[currentPage].content}</p>
        </div>
      </div>
      <div className="controls">
        <button onClick={handlePreviousPage} disabled={currentPage === 0}>
          Página Anterior
        </button>
        <button onClick={handleNextPage} disabled={currentPage === pages.length - 1}>
          Siguiente Página
        </button>
      </div>
    </div>
  );
}

export default Page24;
